const EnJobExperience = [
    {
        id: 0,
        company: 'Danone Russia',
        headcount: '(headcount: ~8 500)',
        logo: '/images/logo_danone.jpg',
        position: 'Reporting and Analytics Manager',
        length: 'July 2019 - current (2 years 2 months)',
        desc: 'Internal reporting. Implementation of BI solutions in HR (MicroStrategy, Power BI). Participation in projects as the subject-matter expert (upgrade of payroll system 1C from version 2.5 to 3, implementation of Service Now, lead regression testing of SAP SuccessFactors). Data audits.',
        achievements: [
            'Unification and automation of data collection process for internal reporting within the CIS Region',
            'Design, development and implementation of reporting and dashboards in Power BI',
            'Covid-19 reporting process design and implementation',
        ],
    },
    {
        id: 1,
        company: 'X5: Pyaterochka',
        headcount: '(headcount: ~180 000)',
        logo: '/images/logo_x5.png ',
        position: 'Head of HR Budgeting and Reporting',
        length: 'December 2018 — June 2019 (7 months)',
        desc: 'Preparation, calculation and approval of people costs budget. Budget execution control. Implementation of BI solutions (QlikSense, Tableau). 3 employees in direct report',
        achievements: [
            'Building-up a new team, improvements of existing and building of new processes',
            'Automation of regular reporting and dashboard on QlikSense',
        ],
    },
    {
        id: 2,
        company: 'METRO Cash & Carry',
        headcount: '(headcount: ~18 000)',
        logo: '/images/logo_metro.png',
        position: 'HR Budgeting and Reporting Manager',
        length: 'June 2017 — November 2018 (1 year 6 months)',
        desc: 'Preparation, calculation and approval of people costs budget, conduction forecasts quarterly, budget execution analysis, data visualization. Organizational structure management control. Regular reporting automation and end-users training. 1 employee in direct report.',
        achievements: [
            'Target structure calculations automation in Excel (Power Query, VBA)',
            'Implementation of act vs plan analysis process',
            'Development and implementation of custom add-in for Excel to simplify the interaction with the file and eliminate manual errors in forecasting the headcount and people costs',
        ],
    },
    {
        id: 3,
        company: 'Sheremetyevo International Airport',
        headcount: '(headcount: ~ 6 500)',
        logo: '/images/logo_sharik.png',
        position: 'Head of HR Costs Planning and Forecasting',
        length: 'January 2017 — May 2017 (5 months)',
        desc: 'SAP PCP implementation and system integrations project lead. Preparation and implementation control of technical requirements and specifications for making changes and enhancements in SAP HR. Headcount and costs planning and forecasting process coordination, act vs plan analysis.2 employees in direct report and 1 dotted-line',
        achievements: [
            'Successful launch of headcount planning in web-interface',
        ],
    },
    {
        id: 4,
        company: 'Sheremetyevo International Airport',
        headcount: '(headcount: ~ 6 500)',
        logo: '/images/logo_sharik.png',
        position: 'Senior Budgeting and Reporting Manager',
        length: 'April 2015 — December 2016 (1 year 9 months)',
        desc: 'SAP (HCM, BW) implementation subject-matter expert (methodology, technical requirements, project documentation, quality assurance, end users’ trainings). Data quality control. Budgeting and forecasting lead, budget execution control, act vs plan analysis.',
        achievements: [
            'Budgeting and forecasting automation with VBA in Excel (versioning, backups, preparation final form for approvals)',
            'Development of reporting from scratch: 7 new reports created in SAP HR. As a result, first ever HR KPIs Dashboard developed and published for top-management',
        ],
    },
    {
        id: 5,
        company: 'PepsiCo Russia',
        headcount: '(headcount: ~ 25 000)',
        logo: '/images/logo_pepsico.svg',
        position: 'HR Planning and Controlling Specialist',
        length: 'August 2014 — March 2015 (8 months)',
        desc: 'Development and implementation of data collection process. Data consolidation, budget analysis and calculations. Preparation of data for act vs plan analysis. Budget execution control.',
        achievements: [],
    },
    {
        id: 6,
        company: 'PepsiCo Russia',
        headcount: '(headcount: ~ 25 000)',
        logo: '/images/logo_pepsico.svg',
        position: 'Reporting Specialist',
        length: 'August 2013 — July 2014 (1 year)',
        desc: 'Participated as subject-matter expert in systems integrations and data migration to SAP HR project. Data quality assurance, testing, end-users training. Regular HR reporting. Intranet administrator for data and reports distribution, ensure reports and data relevance on shared resources, data access management.',
        achievements: [],
    },
    {
        id: 7,
        company: 'Belgrankorm-Velikiy Novgorod',
        headcount: '(headcount: ~1 200)',
        logo: '/images/logo_bgk.png',
        position: 'Leading economist',
        length: 'May 2012 — July 2013 (1 year 3 month)',
        desc: 'Budget and monthly bonuses calculation. Organizational structure design and management. Work time analysis and control.',
        achievements: [],
    },
]

const RuJobExperience = [
    {
        id: 0,
        company: 'Danone Russia',
        headcount: '(численность компании: ~6 500)',
        logo: '/images/logo_danone.png',
        position:
            'Менеджер по развитию систем отчетности и работе с аналитическими данными',
        length: 'Июль 2019 — по настоящее время (2 года 2 месяца)',
        desc: 'Внутрикорпоративная отчетность. Внедрение BI решений (MicroStrategy, Power BI). Участие в проектах в качестве subject-matter expert (Обновление 1С версии 2.5 до 3. Внедрение Service Now. Организация и проведение регрессионного тестирования SAP SuccessFactors). Аудит данных.',
        achievements: [
            'Унификация и автоматизация сбора данных для внутренней отчетности в рамках СНГ',
            'Создание управленческой отчетности на базе Power BI',
            'Оперативная отчетность по Covid-19 (настройка процесса сбора данных с помощью python и их анализ)',
        ],
    },
    {
        id: 1,
        company: 'Х5: Пятерочка',
        headcount: '(численность компании: ~180 000)',
        logo: '/images/logo_x5.png',
        position: 'Начальник отдела бюджетирования и аналитики',
        length: 'Декабрь 2018 — Июнь 2019 (7 месяцев)',
        desc: 'Составление и подготовка на утверждение бюджета затрат на персонал. Анализ и контроль исполнения бюджета. Внедрение аналитических платформ BI (QlikSense, Tableau). В прямом подчинении 3 человека.',
        achievements: [
            'Формирование команды с нуля, улучшение существующих и выстраивание новых процессов',
            'Автоматизация подготовки управленческой отчетности, а также регулярных отчетов на базе QlikSense',
        ],
    },
    {
        id: 2,
        company: 'METRO Cash & Carry',
        headcount: '(численность компании: ~18 000)',
        logo: '/images/logo_metro.png',
        position: 'Менеджер по бюджетированию и отчетности',
        length: 'Июнь 2017 — Ноябрь 2018 (1 год 6 месяцев)',
        desc: 'Составление и подготовка на утверждение бюджета затрат на персонал, ежеквартальное прогнозирование и анализ исполнения бюджета, визуализация данных. Методологический контроль ведения отчетности, организационной структуры. Автоматизация регулярных отчетов и обучение конечных пользователей. В прямом подчинении 1 человек.',
        achievements: [
            'Автоматизация расчета целевой структуры магазинов в Excel (Power Query, VBA)',
            'Внедрение процесса формирования план-факт анализа',
            'Создание пользовательской надстройки в Excel для упрощения работы с файлом и исключения ручных ошибок при прогнозировании численности и расходов на персонал',
        ],
    },
    {
        id: 3,
        company: 'Шереметьево Международный Аэропорт',
        headcount: '(численность компании: ~ 6 500)',
        logo: '/images/logo_sharik.png',
        position:
            'Начальник сектора планирования и прогнозирования затрат на персонал',
        length: 'Январь 2017 — Май 2017 (5 месяцев)',
        desc: 'Лидирование проекта по внедрению платформы SAP PCP для автоматизации процесса бюджетирования затрат на персонал, интеграция учетных систем. Разработка и контроль реализации технических заданий на внесение дополнений, изменений в систему SAP HR. Контроль и координация процесса планирования, прогнозирования численности и бюджета затрат на персонал, план-факт анализ отклонений. В прямом подчинении 2 человека, и 1 человек в функциональном подчинении',
        achievements: ['Запуск web-интерфейса для планирования численности'],
    },
    {
        id: 4,
        company: 'Шереметьево Международный Аэропорт',
        headcount: '(численность компании: ~ 6 500)',
        logo: '/images/logo_sharik.png',
        position: 'Главный специалист Службы бюджетирования затрат на персонал',
        length: 'Апрель 2015 — Декабрь 2016 (1 год 9 месяцев)',
        desc: 'Участие в проектах по внедрению модулей SAP (HCM, BW): разработка методологий, требований и документации по проектам, составление технических заданий, тестирование, и обучение конечных пользователей. Контроль и обеспечение высокого качества данных в системе. План-факт анализ затрат на персонал.',
        achievements: [
            'Автоматизация формирования бюджета затрат на персонал с помощью VBA на Excel (версионность, формирование итоговых форм на утверждение, снятие бекапов',
            'Настройка и внедрение отчетности с нуля – разработка и реализация 7 отчетов в SAP HR (отчеты по активным сотрудникам, принятым, уволенным, штатное расписание, среднесписочная численность, резервы отпусков, отсутствия). Как результат - настройка HR Dashboard из полученных данных (расходы на персонал, план-факт анализ, численность, текучесть, абсентеизм, резервы на отпуска).',
        ],
    },
    {
        id: 5,
        company: 'PepsiCo Russia',
        headcount: '(численность компании: ~ 25 000)',
        logo: '/images/logo_pepsico.svg',
        position: ' Специалист по планированию и контролю затрат на персонал',
        length: 'Август 2014 — Март 2015 (8 месяцев)',
        desc: 'Разработка и внедрение процесса сбора данных для дальнейшего планирования затрат на персонал. Консолидация данных, расчет бюджета, и анализ. Формирование и подготовка данных для план-факт анализа и его коммуникация бизнесу, контроль исполнения бюджета.',
        achievements: [],
    },
    {
        id: 6,
        company: 'PepsiCo Russia',
        headcount: '(численность компании: ~ 25 000)',
        logo: '/images/logo_pepsico.svg',
        position: 'Специалист по отчетности',
        length: 'Август 2013 — Июль 2014 (1 год)',
        desc: 'Участие в проекте по интеграции систем и миграции данных из системы Boss-Kadrovik в систему SAP HR, обеспечение качества данных, тестирование, обучение конечных пользователей. Формирование и поддержка регулярных HR отчетов (headcount, turnover, HR KPIs и HR Dashboard, и т.д.). Администрирование внутреннего портала для хранения данных, обеспечение актуальности данных на общих ресурсах и предоставление информационного доступа к подготовленным данным.',
        achievements: [],
    },
    {
        id: 7,
        company: 'ООО "Белгранкорм - Великий Новгород',
        headcount: '(численность компании: ~ 1 200)',
        logo: '/images/logo_bgk.png',
        position:
            'Ведущий экономист отдела организации труда и заработной платы',
        length: 'Май 2012 — Июль 2013 (1 год 3 месяца)',
        desc: 'Расчет и распределение фонда оплаты труда по результатам производственных показателей, расчет показателей премирования. Составление, ведение и контроль штатного расписания, графиков работы, проверка табелей учета рабочего времени. Проведение хронометражей и фотографий рабочего дня',
        achievements: [],
    },
]
